
package Vista;

import Controlador.ControladorMenu;
import Modelo.Entidades.SesionUsuario;
import java.awt.CardLayout;
import java.sql.SQLException;

/**
 *
 * @author Jesus
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private PnlInicio pnlInicio;
    private PnlVenta pnlVenta;
    private PnlCompra pnlCompra;
    private PnlInventario pnlInventario;
    private PnlReporte pnlReporte;
    private PnlAdmin pnlAdmin;
    private SesionUsuario sesionUsuario;
    private ControladorMenu conMenu;
    
    /**
     * Creates new form FrmMenuPrincipal
     */
    
    public FrmMenuPrincipal(){
        initComponents();   
    }
    
    public FrmMenuPrincipal(SesionUsuario sesionUsuario) throws SQLException {
        initComponents();
        iniciarCardLayout();
        this.sesionUsuario = sesionUsuario;
        this.conMenu = new ControladorMenu(this);
        this.setLocationRelativeTo(null);  
        habilitarBotones();
    }
    
    public SesionUsuario getSesion(){return sesionUsuario;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSlider = new javax.swing.JPanel();
        btnVenta = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnAdministrar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda Mass | Menu Principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSlider.setBackground(new java.awt.Color(255, 255, 102));
        pnlSlider.setPreferredSize(new java.awt.Dimension(350, 800));

        btnVenta.setBackground(new java.awt.Color(232, 232, 232));
        btnVenta.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(0, 61, 117));
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito.png"))); // NOI18N
        btnVenta.setText("VENTA");
        btnVenta.setEnabled(false);
        btnVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenta.setPreferredSize(new java.awt.Dimension(200, 80));
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        btnCompra.setBackground(new java.awt.Color(232, 232, 232));
        btnCompra.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        btnCompra.setForeground(new java.awt.Color(0, 61, 117));
        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compra.png"))); // NOI18N
        btnCompra.setText("COMPRA");
        btnCompra.setEnabled(false);
        btnCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompra.setPreferredSize(new java.awt.Dimension(200, 80));
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(232, 232, 232));
        btnInventario.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(0, 61, 117));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.png"))); // NOI18N
        btnInventario.setText("REGISTRO");
        btnInventario.setEnabled(false);
        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventario.setPreferredSize(new java.awt.Dimension(200, 80));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnReporte.setBackground(new java.awt.Color(232, 232, 232));
        btnReporte.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(0, 61, 117));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        btnReporte.setText("REPORTE");
        btnReporte.setEnabled(false);
        btnReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReporte.setPreferredSize(new java.awt.Dimension(200, 80));
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnAdministrar.setBackground(new java.awt.Color(232, 232, 232));
        btnAdministrar.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        btnAdministrar.setForeground(new java.awt.Color(0, 61, 117));
        btnAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrador.png"))); // NOI18N
        btnAdministrar.setText("ADMIN");
        btnAdministrar.setEnabled(false);
        btnAdministrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdministrar.setPreferredSize(new java.awt.Dimension(200, 80));
        btnAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_tienda_login.png"))); // NOI18N

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 102));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar_sesion.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSliderLayout = new javax.swing.GroupLayout(pnlSlider);
        pnlSlider.setLayout(pnlSliderLayout);
        pnlSliderLayout.setHorizontalGroup(
            pnlSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSliderLayout.createSequentialGroup()
                .addGroup(pnlSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion)
                    .addGroup(pnlSliderLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnlSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSliderLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblLogo)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlSliderLayout.setVerticalGroup(
            pnlSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSliderLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(55, 55, 55)
                .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        getContentPane().add(pnlSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlContenido.setBackground(new java.awt.Color(232, 232, 232));
        pnlContenido.setPreferredSize(new java.awt.Dimension(850, 800));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        conMenu.cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        cardLayout.show(pnlContenido, "VENTA");
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        cardLayout.show(pnlContenido, "COMPRA");
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        cardLayout.show(pnlContenido, "INVENTARIO");
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        cardLayout.show(pnlContenido, "REPORTE");
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarActionPerformed
        cardLayout.show(pnlContenido, "ADMIN");
    }//GEN-LAST:event_btnAdministrarActionPerformed

    private void iniciarCardLayout() throws SQLException{
        cardLayout = new CardLayout();
        pnlContenido.setLayout(cardLayout);
        crearPaneles();
        
    }
    
    private void crearPaneles() throws SQLException{
        pnlInicio = new PnlInicio();
        pnlContenido.add(pnlInicio, "INICIO");
        pnlVenta = new PnlVenta(this);
        pnlContenido.add(pnlVenta, "VENTA");
        pnlCompra = new PnlCompra(this);
        pnlContenido.add(pnlCompra, "COMPRA");
        pnlInventario = new PnlInventario(this);
        pnlContenido.add(pnlInventario, "INVENTARIO");
        pnlReporte = new PnlReporte(this);
        pnlContenido.add(pnlReporte, "REPORTE");
        pnlAdmin = new PnlAdmin(this);
        pnlContenido.add(pnlAdmin, "ADMIN");
    }
    
    private void habilitarBotones(){
        String rol = sesionUsuario.getNombreRol();
        
        if (rol.equals("Administrador") || rol.equals("Cajero")){
            btnVenta.setEnabled(true);
            btnCompra.setEnabled(true);
        }
        if (rol.equals("Administrador") || rol.equals("Supervisor")){
            btnReporte.setEnabled(true);
        }
        if (rol.equals("Administrador") || rol.equals("Almacenero")){
            btnInventario.setEnabled(true);
        }
        if (rol.equals("Administrador")){
            btnAdministrar.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmMenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlSlider;
    // End of variables declaration//GEN-END:variables
}
