
package Vista;

import Controlador.ControladorVenta;
import Modelo.Estructuras.NodoLista;
import Utilidades.Mensajes;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jesus
 */
public class PnlVenta extends javax.swing.JPanel {
    private ControladorVenta conVenta;
    private DefaultTableModel modeloTabla;
    private FrmMenuPrincipal frmMenuPrincipal;
    private double importeMonto;
    private double vueltoMonto;
    
    /**
     * Creates new form pnlContenido
     */
    public PnlVenta() {
        initComponents();
    }
    
    public PnlVenta(FrmMenuPrincipal frmMenuPrincipal) {
        initComponents();
        this.conVenta = new ControladorVenta(frmMenuPrincipal, this);
        this.frmMenuPrincipal = frmMenuPrincipal;
        inicializarTabla();
        configurarBotones();
    }

    public double getImporteMonto() {return importeMonto;}
    public double getVueltoMonto() {return vueltoMonto;}
    
    public void setImporteMonto(double importeMonto) {this.importeMonto = importeMonto;}
    public void setVueltoMonto(double vueltoMonto) {this.vueltoMonto = vueltoMonto;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarID = new javax.swing.JButton();
        btnBuscarCB = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();
        btnMonto = new javax.swing.JButton();
        btnConfirmarVenta = new javax.swing.JButton();
        jspCarrito = new javax.swing.JScrollPane();
        jtbleCarrito = new javax.swing.JTable();
        lblImporte = new javax.swing.JLabel();
        lblVuelto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblImporteValor = new javax.swing.JLabel();
        lblVueltoValor = new javax.swing.JLabel();
        lblTotalValor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 232, 232));
        setPreferredSize(new java.awt.Dimension(850, 800));

        btnBuscarID.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscarID.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnBuscarID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarID.png"))); // NOI18N
        btnBuscarID.setText("Añadir por ID");
        btnBuscarID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnBuscarCB.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscarCB.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnBuscarCB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarCB.png"))); // NOI18N
        btnBuscarCB.setText("Añadir por CB");
        btnBuscarCB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnModificar.setBackground(new java.awt.Color(255, 255, 102));
        btnModificar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnEliminar.setBackground(new java.awt.Color(255, 255, 102));
        btnEliminar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnVaciar.setBackground(new java.awt.Color(255, 255, 102));
        btnVaciar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnVaciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnVaciar.setText("Cancelar");
        btnVaciar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnMonto.setBackground(new java.awt.Color(255, 255, 102));
        btnMonto.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnMonto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/importe.png"))); // NOI18N
        btnMonto.setText("Monto");
        btnMonto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnConfirmarVenta.setBackground(new java.awt.Color(255, 255, 102));
        btnConfirmarVenta.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnConfirmarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/procesar.png"))); // NOI18N
        btnConfirmarVenta.setText("Procesar");
        btnConfirmarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jtbleCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbleCarrito.setGridColor(new java.awt.Color(204, 204, 204));
        jtbleCarrito.setRowHeight(35);
        jspCarrito.setViewportView(jtbleCarrito);

        lblImporte.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblImporte.setText("Importe:");

        lblVuelto.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblVuelto.setText("Vuelto:");

        lblTotal.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblTotal.setText("Total:");

        lblImporteValor.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblImporteValor.setText("S/. 0.00");

        lblVueltoValor.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblVueltoValor.setText("S/. 0.00");

        lblTotalValor.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblTotalValor.setText("S/. 0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVaciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarID))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVuelto)
                                    .addComponent(lblImporte)
                                    .addComponent(lblTotal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblImporteValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblVueltoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jspCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnBuscarCB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImporte, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImporteValor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVueltoValor)
                            .addComponent(lblVuelto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(lblTotalValor))
                        .addGap(27, 27, 27)
                        .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addComponent(jspCarrito))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTabla(){
        String[] columnasTablaCarrito = {"Código", "Producto", "Cantidad", "Precio Unit.", "Subtotal"};
        modeloTabla = new DefaultTableModel(columnasTablaCarrito, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }; 
        jtbleCarrito.setModel(modeloTabla);
        jtbleCarrito.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jtbleCarrito.getTableHeader().setForeground(Color.BLACK);
        jtbleCarrito.getTableHeader().setPreferredSize(new Dimension(0, 45));
        jtbleCarrito.getTableHeader().setReorderingAllowed(false);
        jtbleCarrito.getTableHeader().setBackground(new Color(255, 255, 102));
        
        configurarColumnasCarrito();
    }
    
    private void configurarColumnasCarrito(){
        int[] anchos = {40, 160, 60, 85, 55};
        for (int i = 0; i < anchos.length; i++){
            TableColumn columna = jtbleCarrito.getColumnModel().getColumn(i);
            columna.setPreferredWidth(anchos[i]);
            columna.setResizable(false);
        }
    }
    
    public void actualizarImporte(double valor){
        importeMonto = valor;
        lblImporteValor.setText(String.format("S/. %.2f", valor));
    }
    
    public void actualizarVuelto(){
        vueltoMonto = importeMonto - conVenta.getLista().montoTotal();
        lblVueltoValor.setText(String.format("S/. %.2f", vueltoMonto));
    }
    
    public void actualizarTotal(double valor){
        lblTotalValor.setText(String.format("S/. %.2f", valor));
    }
    
    private void configurarBotones() {
        btnBuscarID.addActionListener(e -> conVenta.agregarPorId());
        btnBuscarCB.addActionListener(e -> conVenta.agregarPorCB());
        btnEliminar.addActionListener(e -> conVenta.eliminar(obtenerIdTabla()));
        btnModificar.addActionListener(e -> conVenta.modificar(obtenerIdTabla()));
        btnConfirmarVenta.addActionListener(e -> conVenta.procesarVenta());
        btnVaciar.addActionListener(e -> conVenta.vaciar());
        btnMonto.addActionListener(e -> conVenta.setImporte());
    }

    private int obtenerIdTabla(){
        try {
            int filaSeleccionada = jtbleCarrito.getSelectedRow();
        
            if (filaSeleccionada >= 0){
                int id = Integer.parseInt(jtbleCarrito.getValueAt(filaSeleccionada, 0).toString());
                return id;
            } else {
                Mensajes.mostrarAd(frmMenuPrincipal, "!Espere!", "Seleccione una opcion antes");
            }
        } catch (NumberFormatException e){
            Mensajes.mostrarError(frmMenuPrincipal, "Error", "Error al obtener el ID del producto.");
        }
        return -1;
    }
    
    public void actualizarCarrito(){
        modeloTabla.setRowCount(0);
        NodoLista puntero = conVenta.getLista().getCabeza();
        while(puntero != null){
            Object[] fila = {
                puntero.getProducto().getIdProducto(),
                puntero.getProducto().getNombre(),
                puntero.getCantidad(),
                String.format("S/. %.2f", puntero.getProducto().getPrecio()),
                String.format("S/. %.2f", puntero.subTotal())
            };
            modeloTabla.addRow(fila);
            puntero = puntero.getSiguiente();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCB;
    private javax.swing.JButton btnBuscarID;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMonto;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JScrollPane jspCarrito;
    private javax.swing.JTable jtbleCarrito;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblImporteValor;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValor;
    private javax.swing.JLabel lblVuelto;
    private javax.swing.JLabel lblVueltoValor;
    // End of variables declaration//GEN-END:variables
}
